name: "yolo_preprocess"
backend: "dali"
max_batch_size: 50
input [
{
        name: "DALI_INPUT"
        data_type: TYPE_UINT8 
        dims: [ -1 ]
}
]

output [
{
        name: "DALI_OUTPUT"
        data_type: TYPE_FP32
        dims: [ 3, 640, 640 ]
}
]
